name: Easy-Custom-Enchants
version: '1.0-SNAPSHOT'
main: me.gecko.easyCustomEnchants.EasyCustomEnchants
api-version: '1.21'
description: Easily create custom enchantments
commands:
  createenchantment:
    description: Create a custom enchantment
    usage: /createenchantment <name> <maxLevel> <type> <conflict> <description>
    permission: op
    permission-message: §cYou need to have operator permissions to run this command!